//
// Created by israe on 24/10/2024.
//

#include "ejercicio5.h"
#include <iostream>
#include <stdexcept>

void lanzaExcepcionParte5() {
    throw std::runtime_error("Error en la funci√≥n lanzaExcepcionParte5");
}