
#include "ejercicio6.h"
#include<iostream>
#include<stdexcept>

void lanzaExcepcionParte6() {
    throw std::runtime_error("Error en la funci√≥n lanzaExcepcion");
}